---

a1:
    carbon: [1/2, 1/2, 0]
    vacancy: [1/2, 1/2, 1/2]
    n_carbon: 1
    n_vacancy: 1

a2:
    carbon: [1, 0, 1/2]
    vacancy: [1/2, 1/2, 1/2]
    n_carbon: 1
    n_vacancy: 1


b1:
    carbon: [1/2, 1, 1/2]
    vacancy: [[1/2, 1/2, 1/2], [1/2, 3/2, 1/2]]
    n_carbon: 1
    n_vacancy: 2


b2:
    carbon: [1, 1/2,0] 
    vacancy: [[1/2, 1/2, 1/2], [1/2, 3/2, 1/2]]
    n_carbon: 1
    n_vacancy: 2
    vacancy_type: v2

b3:
    carbon: [1/2, 0, 1/2] 
    vacancy: [[1/2, 1/2, 1/2], [1/2, 3/2, 1/2]]
    n_carbon: 1
    n_vacancy: 2
    vacancy_type: v2


c1:
    carbon: [1/2, 1/2, 1]
    vacancy: [[1/2, 1/2, 1/2], [1, 0, 0]]
    n_carbon: 1
    n_vacancy: 2
    vacancy_type: v3


c2:
    carbon: [1/2, 1/2, 0]
    vacancy: [[1/2, 1/2, 1/2], [1, 0, 0]]
    n_carbon: 1
    n_vacancy: 2
    vacancy_type: v3


d:
    carbon: [[1/2, 1/2, 0], [1/2, 1/2, 1]]
    vacancy: []
    n_carbon: 2
    n_vacancy: 0
    vacancy_type: null

e:
    carbon: [[1, 1/2, 0], [1/2, 1/2, 1]]
    vacancy: []
    n_carbon: 2
    n_vacancy: 0
    vacancy_type: null


f:
    carbon: [[1, 1/2, 0], [0, 3/2, 1]]
    vacancy: []
    n_carbon: 2
    n_vacancy: 0
    vacancy_type: null



g:
    carbon: [[1, 0, 1/2], [1, 1, 1/2]]
    vacancy: []
    n_carbon: 2
    n_vacancy: 0
    vacancy_type: null
  
h:
    carbon: [[1/2, 1/2, 1], [1/2, 1, 1/2]]
    vacancy: []
    n_carbon: 2
    n_vacancy: 0
    vacancy_type: null
  
i:
    carbon: [[1/2, 1/2, 1], [1, 0, 1/2]]
    vacancy: []
    n_carbon: 2
    n_vacancy: 0
    vacancy_type: null
  
j:
    carbon: [[1/2, 1/2, 0], [1/2, 1/2, 1]]
    vacancy: [1/2, 1/2, 1/2]
    n_carbon: 2
    n_vacancy: 1
    vacancy_type: v1
  
 
k:
    carbon: [[1/2, 1/2, 0], [1/2, 0, 1/2]]
    vacancy: [1/2, 1/2, 1/2]
    n_carbon: 2
    n_vacancy: 1
    vacancy_type: v1
 
 
l:
    carbon: [[1/2, 1/2, 1/4], [1/2, 1/2, 3/4]]
    vacancy: [1/2, 1/2, 1/2]
    n_carbon: 2
    n_vacancy: 1
    vacancy_type: v1
 
m:
    carbon: [[1/2, 3/4, 1/4], [1/2, 1/4, 3/4]]
    vacancy: [1/2, 1/2, 1/2]
    n_carbon: 2
    n_vacancy: 1
    vacancy_type: v1


