---

data:
    input: ./input/Fe.poscar
    SpaceGroup: BCC
    SpaceGroupNumber: 229
    MateiralID: mp-13
    load_args:
        format: vasp
        index: 0
    cwd: .

calculator:
    calc_type: sevennet
    path: /data2/jinvk/MLP
    prefix: ompa
    calc_args:
        device: cuda
        modal: omat24
    modal: omat24
    extension: pth

pair:
    save: ./pair
    run: true
    supercell: [4, 4, 4]

    solute: ['Cu', 'Mn', 'Ni', 'Si']
    position:
        base: [1, 0, 0]
        1nn: [0.5, 0.5, 0.5]
        2nn: [1, 1, 0]
        3nn: [0, 0, 1]
        4nn: [0.5, 1.5, 0.5]
        5nn: [0, 1, 1]
    opt: ortho

opt:
    vc-relax:
        fmax: 0.001
        steps: 10000
        optimizer: fire
        cell_filter: unitcell
        mask: [1, 1, 1, 1, 1, 1]
        fix_symm: false
        logfile: ./mlip/ompa/omat24/./vc_relax.log
    ortho:
        fmax: 0.001
        steps: 10000
        optimizer: fire
        cell_filter: unitcell
        mask: [1, 1, 1, 0, 0, 0]
        fix_symm: false
        logfile: ./mlip/ompa/omat24/./ortho.log
    relax:
        fmax: 0.001
        steps: 10000
        optimizer: fire
        cell_filter: false
        fix_symm: false
        logfile: ./mlip/ompa/omat24/./relax.log
    z:
        fmax: 0.001
        steps: 10000
        optimizer: fire
        cell_filter: unitcell
        mask: [0, 0, 1, 0, 0, 0]
        fix_symm: false
        logfile: ./mlip/ompa/omat24/z_dir_opt.log
    stiffness:
        verbose: true
        delta: 0.005
        N_steps: 4
        fmax: 0.0001
        steps: 1000
        graphics: false

root: /data2_1/jinvk/25_Fe/August

cwd: /data2_1/jinvk/25_Fe/August/./mlip/ompa/omat24

output: /data2_1/jinvk/25_Fe/August/output
...
